job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    /**scm {
        git("https://github.com/schmuesm/Jenkins_Upgradev3.git", 'master')
    }*/
    scm {
       git {
              remote {
	           url('https://github.com/schmuesm/Jenkins_Upgradev3.git')
	              credentials('GitHub User')
               }
               branch('*/master')
	}
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
